/**
 * The full anime genre taxonomy (demographics + themes + formats), used to
 * tag productions at creation and in the config editor. The complete
 * industry list — demographics, core genres, themes, settings, activities,
 * aesthetics and the mature/adult block (Pro-gated).
 */
export const ANIME_GENRES = [
  // demographics
  'Shounen',
  'Shoujo',
  'Seinen',
  'Josei',
  'Kodomo',
  // core
  'Action',
  'Adventure',
  'Comedy',
  'Drama',
  'Romance',
  'Slice of Life',
  'Fantasy',
  'Sci-Fi',
  'Supernatural',
  'Horror',
  'Mystery',
  'Psychological',
  'Thriller',
  'Suspense',
  'Sports',
  // themes
  'Isekai',
  'Dark Fantasy',
  'Mecha',
  'Cyberpunk',
  'Ecchi',
  'Harem',
  'Reverse Harem',
  'Shounen Ai',
  'Shoujo Ai',
  'Yuri',
  'Yaoi',
  'Otome',
  'Magic',
  'School',
  'Martial Arts',
  'Super Power',
  'Music',
  'Idol',
  'Military',
  'Historical',
  'Samurai',
  'Ninja',
  'Wuxia',
  'Cultivation',
  'Post-Apocalyptic',
  'Survival',
  'Zombie',
  'Vampire',
  'Space',
  'Time Travel',
  'Video Game',
  'Virtual Reality',
  'Detective',
  'Parody',
  'Gag Humor',
  'Gourmet',
  'Medical',
  'Tragedy',
  'Coming of Age',
  'Iyashikei',
  'Workplace',
  'Office',
  'Cooking',
  'Baking',
  'Fashion',
  'Theater',
  'Photography',
  'Travel',
  'Camping',
  'Farming',
  'Agriculture',
  'Pets',
  'Cats',
  'Dogs',
  'Gyaru',
  'Delinquent',
  'Gang',
  'Crime',
  'Mafia',
  'Yakuza',
  'Heist',
  'Espionage',
  'Political',
  'War',
  'Philosophy',
  'Existential',
  'Surreal',
  'Absurdist',
  'Avant-garde',
  'Experimental',
  // settings & aesthetics
  'Steampunk',
  'Dieselpunk',
  'Solarpunk',
  'Mythology',
  'Folklore',
  'Yokai',
  'Kaiju',
  'Tokusatsu',
  'Fairy Tale',
  'High Fantasy',
  'Sword & Sorcery',
  'Space Opera',
  'Western',
  'Viking',
  'Pirate',
  'Underwater',
  'Sky',
  'Desert',
  'Winter',
  'Kimonos',
  'Sakura',
  // activities
  'Racing',
  'Boxing',
  'Sumo',
  'Basketball',
  'Soccer',
  'Baseball',
  'Volleyball',
  'Tennis',
  'Golf',
  'Swimming',
  'Gymnastics',
  'Archery',
  'Kendo',
  'Fencing',
  'Skating',
  'Skiing',
  'Surfing',
  'Esports',
  'Card Game',
  'Board Game',
  'Strategy Game',
  'Mahjong',
  'Shogi',
  // fantasy sub-systems
  'Dungeon',
  'Tower Climbing',
  'Leveling',
  'Guild',
  'Reincarnation',
  'Regression',
  'Demon Lord',
  'Angel',
  'Necromancy',
  'Alchemy',
  'Summoning',
  'Kingdom Building',
  'Aristocracy',
  'Royalty',
  'Knights',
  'Holy War',
  'Merchant',
  'Medicine',
  // performance & craft
  'Dance',
  'Ballet',
  'Orchestra',
  'Band',
  'DJ',
  'Rap',
  'Opera',
  'Circus',
  'Magic Show',
  'Astronomy',
  'Ping Pong',
  'Wrestling',
  'Parkour',
  'Mixed Martial Arts',
  'Badminton',
  'Bowling',
  // ---------------------- mature block (Pro-gated) ----------------------
  'Hentai',
  'Erotica',
  'Adult Drama',
  'Adult Romance',
  'Erotic Fantasy',
  'Erotic Drama',
  'Adult Comedy',
  'Adult Adventure',
  'Adult Fantasy',
  'Adult Isekai',
  'Adult Harem',
  'Adult Yuri',
  'Adult Yaoi',
  'Seduction',
  'Sensual Romance',
  'Explicit Romance',
  'Mature Themes',
  'Adult Horror',
  'Adult Sci-Fi',
  'Adult Thriller',
  'Bishoujo',
  'Biseinen',
  'Succubus',
  'Vampiric Romance',
] as const

export type AnimeGenre = (typeof ANIME_GENRES)[number]

/** The mature/adult block — only visible with Mature Content Mode (Pro) on. */
export const MATURE_BLOCK_START = ANIME_GENRES.indexOf('Hentai')

export const HOT_GENRES: ReadonlySet<string> = new Set([
  'Isekai',
  'Romance',
  'Fantasy',
  'Shounen',
  'Seinen',
  'Ecchi',
  'Harem',
  'Yuri',
  'Psychological',
  'Dark Fantasy',
  'Cultivation',
  'Iyashikei',
])
