/**
 * Phase 6 — scene render builder (pure) + REAL FFmpeg integration.
 *
 * The PNG/WAV fixtures are generated by minimal in-test encoders (deflate +
 * CRC32 for PNG, RIFF/PCM headers for WAV) so FFmpeg decodes REAL files —
 * no fake bytes anywhere.
 */
import { describe, expect, it } from 'vitest'
import { deflateSync } from 'node:zlib'
import { mkdtempSync, writeFileSync, existsSync, statSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import {
  DEFAULT_PRESET_ID,
  exportPresetById,
  sampleCurve,
  type KeyframeRecord,
  type TimelineBundle,
} from '@mirai/shared'
import { CreativeService } from '../src/creative/creativeService'
import { MediaService } from '../src/media/mediaService'
import { RenderService } from '../src/render/renderService'
import { buildSceneRenderSpec } from '../src/render/sceneRenderBuilder'
import { StoryboardService } from '../src/storyboard/storyboardService'
import { TimelineService } from '../src/timeline/timelineService'
import { openDatabase } from '../src/db/connection'
import { runMigrations } from '../src/db/migrator'
import { PROJECT_DB_MIGRATIONS } from '../src/db/migrations'
import { makeClock } from './helpers'

// ---------------------------------------------------------------- fixtures

/** Minimal but 100% valid PNG encoder (RGB, no interlace). */
function crc32(buf: Buffer): number {
  let c: number
  let crc = 0xffffffff
  for (let i = 0; i < buf.length; i++) {
    c = (crc ^ buf[i]!) & 0xff
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
    crc = (crc >>> 8) ^ c
  }
  return (crc ^ 0xffffffff) >>> 0
}

function pngChunk(type: string, data: Buffer): Buffer {
  const len = Buffer.alloc(4)
  len.writeUInt32BE(data.length)
  const typeBuf = Buffer.from(type, 'ascii')
  const crc = Buffer.alloc(4)
  crc.writeUInt32BE(crc32(Buffer.concat([typeBuf, data])))
  return Buffer.concat([len, typeBuf, data, crc])
}

function makePng(w: number, h: number, rgb: [number, number, number]): Buffer {
  const ihdr = Buffer.alloc(13)
  ihdr.writeUInt32BE(w, 0)
  ihdr.writeUInt32BE(h, 4)
  ihdr[8] = 8 // bit depth
  ihdr[9] = 2 // RGB
  ihdr[10] = 0
  ihdr[11] = 0
  ihdr[12] = 0
  const raw = Buffer.alloc(h * (1 + w * 3))
  for (let y = 0; y < h; y++) {
    const row = y * (1 + w * 3)
    raw[row] = 0 // filter: none
    for (let x = 0; x < w; x++) {
      raw[row + 1 + x * 3] = rgb[0]
      raw[row + 2 + x * 3] = rgb[1]
      raw[row + 3 + x * 3] = rgb[2]
    }
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    pngChunk('IHDR', ihdr),
    pngChunk('IDAT', deflateSync(raw)),
    pngChunk('IEND', Buffer.alloc(0)),
  ])
}

/** Minimal but 100% valid WAV (PCM 16-bit mono) with a sine tone. */
function makeWav(seconds: number, sampleRate = 8000): Buffer {
  const samples = Math.floor(seconds * sampleRate)
  const dataBytes = samples * 2
  const buf = Buffer.alloc(44 + dataBytes)
  buf.write('RIFF', 0)
  buf.writeUInt32LE(36 + dataBytes, 4)
  buf.write('WAVE', 8)
  buf.write('fmt ', 12)
  buf.writeUInt32LE(16, 16)
  buf.writeUInt16LE(1, 20) // PCM
  buf.writeUInt16LE(1, 22) // mono
  buf.writeUInt32LE(sampleRate, 24)
  buf.writeUInt32LE(sampleRate * 2, 28)
  buf.writeUInt16LE(2, 32)
  buf.writeUInt16LE(16, 34)
  buf.write('data', 36)
  buf.writeUInt32LE(dataBytes, 40)
  for (let i = 0; i < samples; i++) {
    const v = Math.round(Math.sin((2 * Math.PI * 440 * i) / sampleRate) * 6000)
    buf.writeInt16LE(v, 44 + i * 2)
  }
  return buf
}

// ---------------------------------------------------------------- env

function makeEnv(name: string) {
  const dir = mkdtempSync(join(tmpdir(), `mirai-render-${name}-`))
  const db = openDatabase(join(dir, 'project.sqlite'))
  runMigrations(db, PROJECT_DB_MIGRATIONS)
  const clock = makeClock()
  const creative = new CreativeService(db, clock)
  const storyboard = new StoryboardService(db, clock, dir)
  const media = new MediaService(db, clock, dir)
  const timeline = new TimelineService(db, clock)
  const render = new RenderService(storyboard, media, dir, creative, timeline)
  const episode = creative.createEpisode({ season: 1, number: 1, title: 'Episode One' })
  const scene = creative.createScene(episode.id, { title: 'Rooftop dawn' })
  return { dir, db, clock, creative, storyboard, media, timeline, render, scene }
}

/** Bundle fixture for pure builder tests. */
function plainBundleFixture(): TimelineBundle {
  const sceneId = '01HZZZSCENE0000000000000000'
  const trackV = '01HZZZTRACKVIDEO00000000000'
  const trackVoice = '01HZZZTRACKVOICE00000000000'
  const shotA = '01HZZZSHOTA0000000000000000'
  const shotB = '01HZZZSHOTB0000000000000000'
  return {
    sceneId,
    durationSec: 10,
    tracks: [
      { id: trackV, sceneId, kind: 'VIDEO', name: 'Video', orderIndex: 0, muted: false, solo: false, volume: 1, pan: 0, createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-01T00:00:00Z' },
      { id: trackVoice, sceneId, kind: 'VOICE', name: 'Voice', orderIndex: 1, muted: false, solo: false, volume: 1, pan: 0, createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-01T00:00:00Z' },
    ],
    clips: [
      {
        id: '01HZZZCLIPA0000000000000000', trackId: trackV, sourceType: 'SHOT', sourceId: shotA,
        label: 'Wide', startSec: 0, durationSec: 4, inOffsetSec: 0, volume: 1, opacity: 1, blend: 'normal',
        effects: { brightness: 1, contrast: 1, saturate: 1, hue: 0, blur: 0, grayscale: 0, vignette: 0 },
        createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-01T00:00:00Z',
      },
      {
        id: '01HZZZCLIPB0000000000000000', trackId: trackV, sourceType: 'SHOT', sourceId: shotB,
        label: 'Close', startSec: 4, durationSec: 6, inOffsetSec: 0, volume: 1, opacity: 1, blend: 'normal',
        effects: { brightness: 1, contrast: 1, saturate: 1, hue: 0, blur: 0, grayscale: 0, vignette: 0 },
        createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-01T00:00:00Z',
      },
    ],
    markers: [],
    sources: {
      [shotA]: { type: 'SHOT', shotId: shotA, title: 'Wide', frameAssetId: '01HZZZASSETA00000000000000', audioAssetId: null, durationSec: 4, shotType: 'WIDE', cameraMovement: 'STATIC', dialogue: null },
      [shotB]: { type: 'SHOT', shotId: shotB, title: 'Close', frameAssetId: null, audioAssetId: null, durationSec: 6, shotType: 'CLOSE_UP', cameraMovement: 'STATIC', dialogue: null },
    },
  }
}

const preset = exportPresetById(DEFAULT_PRESET_ID)
const noProgress = () => undefined
const noAbort = { aborted: false }

// ---------------------------------------------------------------- builder

describe('sceneRenderBuilder (pure)', () => {
  it('builds inputs, concat and silent-audio fallback for a plain scene', () => {
    const bundle = plainBundleFixture()
    const spec = buildSceneRenderSpec(bundle, new Map(), new Map(), { preset, quality: 'MASTER' })
    const args = spec.args.join(' ')

    // Two video inputs: one real frame, one black fallback for the frameless shot.
    expect(args).toContain('{{ASSET:01HZZZASSETA00000000000000}}')
    expect(args).toContain('color=black:s=1920x1080')
    expect(spec.videoClipCount).toBe(2)
    expect(spec.totalSec).toBeCloseTo(10)

    // Video concat of both clips.
    expect(args).toContain('concat=n=2:v=1:a=0')
    // Silent audio bed keeps the output shape.
    expect(args).toContain('anullsrc=channel_layout=stereo')
    // Master codec settings with the anime tune.
    expect(args).toContain('-tune animation')
    expect(args).toContain('-crf 18')
    expect(args).toContain('-movflags +faststart')
    // PREVIEW switches to the fast profile.
    const preview = buildSceneRenderSpec(bundle, new Map(), new Map(), { preset, quality: 'PREVIEW' })
    expect(preview.args.join(' ')).toContain('-crf 30')
    expect(preview.args.join(' ')).toContain('ultrafast')
  })

  it('bakes camera curves into zoompan piecewise expressions', () => {
    const bundle = plainBundleFixture()
    const shotA = '01HZZZSHOTA0000000000000000'
    const camera = new Map([
      [shotA, new Map([
        ['scale', [
          { id: '01HZZZKF10000000000000000', targetType: 'CAMERA', targetId: shotA, param: 'scale', atSec: 0, value: 1, easing: 'easeInOut', bezier: null, createdAt: 't', updatedAt: 't' },
          { id: '01HZZZKF20000000000000000', targetType: 'CAMERA', targetId: shotA, param: 'scale', atSec: 4, value: 1.5, easing: 'easeInOut', bezier: null, createdAt: 't', updatedAt: 't' },
        ] as KeyframeRecord[]],
      ])],
    ])
    const spec = buildSceneRenderSpec(bundle, camera, new Map(), { preset, quality: 'MASTER' })
    const graph = spec.args[spec.args.indexOf('-filter_complex') + 1]!

    expect(graph).toContain("zoompan=z='if(")
    // EaseInOut is approximated by sub-sampled segments (not a plain two-point lerp).
    const zoompan = /zoompan=z='([^']+)'/.exec(graph)![1]!
    expect(zoompan).toContain('if(lt(on,')
    // The final baked value must reach the keyframe endpoint 1.5.
    expect(zoompan).toContain('1.5')
  })

  it('applies the effects chain (eq/hue/gblur/vignette) matching the preview', () => {
    const bundle = plainBundleFixture()
    bundle.clips[0]!.effects = {
      brightness: 1.2, contrast: 1.1, saturate: 1.3, hue: 30, blur: 2, grayscale: 0.4, vignette: 0.5,
    }
    const spec = buildSceneRenderSpec(bundle, new Map(), new Map(), { preset, quality: 'MASTER' })
    const graph = spec.args[spec.args.indexOf('-filter_complex') + 1]!
    expect(graph).toContain('eq=brightness=0.2:contrast=1.1:saturation=1.3')
    expect(graph).toContain('hue=h=30:s=0.6')
    expect(graph).toContain('gblur=sigma=2')
    expect(graph).toContain('vignette=angle=')
  })

  it('mixes audio with in-point trims, baked automation, placement and mute rules', () => {
    const bundle = plainBundleFixture()
    const trackVoice = bundle.tracks[1]!.id
    const clipA = bundle.clips[0]!
    // Voice clip on the voice track starting at 4s with automation.
    bundle.clips.push({
      ...clipA,
      id: '01HZZZCLIPV0000000000000000',
      trackId: trackVoice,
      sourceType: 'SHOT',
      label: 'voice',
      startSec: 4,
      durationSec: 3,
      inOffsetSec: 0.5,
      volume: 0.8,
    })
    const shotSource = bundle.sources['01HZZZSHOTA0000000000000000']!
    if (shotSource.type === 'SHOT') shotSource.audioAssetId = '01HZZZASSETV00000000000000'

    const automation = new Map<string, KeyframeRecord[]>([
      [`CLIP:${'01HZZZCLIPV0000000000000000'}`, [
        { id: '01HZZZKF30000000000000000', targetType: 'CLIP', targetId: '01HZZZCLIPV0000000000000000', param: 'volume', atSec: 0, value: 0, easing: 'easeOut', bezier: null, createdAt: 't', updatedAt: 't' },
        { id: '01HZZZKF40000000000000000', targetType: 'CLIP', targetId: '01HZZZCLIPV0000000000000000', param: 'volume', atSec: 1, value: 1, easing: 'easeOut', bezier: null, createdAt: 't', updatedAt: 't' },
      ]],
    ])
    const spec = buildSceneRenderSpec(bundle, new Map(), automation, { preset, quality: 'MASTER' })
    const graph = spec.args[spec.args.indexOf('-filter_complex') + 1]!
    expect(spec.audioClipCount).toBe(1)
    expect(graph).toContain('atrim=start=0.5:duration=3')
    expect(graph).toContain("volume='if(lt(t,")
    expect(graph).toContain('adelay=4000|4000')
    expect(graph).toContain('amix=inputs=1:duration=longest:normalize=0')
    // No pan filter for a centered track.
    expect(graph).not.toContain('pan=stereo')

    // Muting the voice track drops its clips from the mix entirely.
    bundle.tracks[1]!.muted = true
    const mutedSpec = buildSceneRenderSpec(bundle, new Map(), automation, { preset, quality: 'MASTER' })
    expect(mutedSpec.audioClipCount).toBe(0)
  })

  it('composites extra video tracks via overlay with opacity', () => {
    const bundle = plainBundleFixture()
    const trackV2 = '01HZZZTRACKVID20000000000000'
    bundle.tracks.push({
      id: trackV2, sceneId: bundle.sceneId, kind: 'VIDEO', name: 'Overlay', orderIndex: 1,
      muted: false, solo: false, volume: 1, pan: 0,
      createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-01T00:00:00Z',
    })
    bundle.clips.push({
      ...bundle.clips[0]!,
      id: '01HZZZCLIPO0000000000000000',
      trackId: trackV2,
      opacity: 0.5,
      startSec: 0,
      durationSec: 2,
    })
    const spec = buildSceneRenderSpec(bundle, new Map(), new Map(), { preset, quality: 'MASTER' })
    const graph = spec.args[spec.args.indexOf('-filter_complex') + 1]!
    expect(graph).toContain('format=yuva420p')
    expect(graph).toContain('colorchannelmixer=aa=0.5')
    expect(graph).toContain('overlay=0:0')
  })

  it('samples eased/bézier curves exactly like the shared playback math', () => {
    const curve = [
      { atSec: 0, value: 0, easing: 'bezier' as const, bezier: [0.42, 0, 0.58, 1] as [number, number, number, number] },
      { atSec: 2, value: 1, easing: 'linear' as const, bezier: null },
    ]
    expect(sampleCurve(curve, 1)).toBeGreaterThan(0.45)
    expect(sampleCurve(curve, 1)).toBeLessThan(0.55)
    expect(sampleCurve(curve, 3)).toBeCloseTo(1)
  })
})

// ---------------------------------------------------------------- integration

describe('RenderService scene/episode renders (REAL FFmpeg)', () => {
  const ffmpeg = RenderService.detect()

  it.skipIf(!ffmpeg.available)('renders a full scene timeline to a real playable MP4', async () => {
    const env = makeEnv('integration')
    // Real assets: 32x32 PNG frame + 1.5s sine WAV.
    const frameFile = join(env.dir, 'frame.png')
    writeFileSync(frameFile, makePng(32, 32, [240, 130, 200]))
    const wavFile = join(env.dir, 'line.wav')
    writeFileSync(wavFile, makeWav(1.5))

    const shotA = env.storyboard.createShot(env.scene.id, {
      title: 'Dawn wide', durationSeconds: 2,
    })
    const shotB = env.storyboard.createShot(env.scene.id, {
      title: 'Promise close', durationSeconds: 3,
    })
    env.storyboard.importFrame(shotA.id, frameFile)
    env.storyboard.importVoice(shotA.id, wavFile)
    // Camera move on shot B (frameless → black segment with a real zoompan).
    env.timeline.keyframes.upsert({
      targetType: 'CAMERA', targetId: shotB.id, param: 'scale', atSec: 0, value: 1,
    })
    env.timeline.keyframes.upsert({
      targetType: 'CAMERA', targetId: shotB.id, param: 'scale', atSec: 3, value: 1.4, easing: 'easeInOut',
    })

    const bundle = env.timeline.buildFromScene(env.scene.id)
    expect(bundle.clips.length).toBeGreaterThanOrEqual(3)

    const result = await env.render.renderScene({
      sceneId: env.scene.id,
      presetId: DEFAULT_PRESET_ID,
      quality: 'PREVIEW',
      reportProgress: noProgress,
      signal: noAbort,
    })

    expect(existsSync(result.outputPath)).toBe(true)
    const stats = statSync(result.outputPath)
    expect(stats.size).toBeGreaterThan(1_000)
    expect(result.kind).toBe('SCENE')
    expect(result.durationSec).toBeCloseTo(5, 1)
    // ffprobe (same family install as ffmpeg) confirms playability + duration.
    const probed = env.render.probeDuration(result.outputPath)
    expect(probed).not.toBeNull()
    expect(probed!).toBeGreaterThan(4)
    expect(probed!).toBeLessThan(6)
    expect(env.render.probeResolution(result.outputPath)).toBe('1920x1080')

    // Output center lists the produced file.
    const outputs = env.render.listOutputs()
    expect(outputs.some((o) => o.path === result.outputPath && o.kind === 'SCENE')).toBe(true)

    // deleteOutput enforces the exports/ sandbox.
    env.render.deleteOutput(result.outputPath)
    expect(existsSync(result.outputPath)).toBe(false)
  }, 120_000)

  it.skipIf(!ffmpeg.available)('refuses to render scenes/episodes without timelines', async () => {
    const env = makeEnv('guards')
    await expect(
      env.render.renderScene({
        sceneId: env.scene.id, presetId: DEFAULT_PRESET_ID, quality: 'MASTER',
        reportProgress: noProgress, signal: noAbort,
      }),
    ).rejects.toThrow(/no timeline/i)
    // The scene exists but has no timeline → actionable message.
    await expect(
      env.render.renderEpisode({
        episodeId: env.creative.listEpisodes()[0]!.id, presetId: DEFAULT_PRESET_ID, quality: 'MASTER',
        reportProgress: noProgress, signal: noAbort,
      }),
    ).rejects.toThrow(/build these scenes/i)
    // Unknown episode → NOT_FOUND.
    await expect(
      env.render.renderEpisode({
        episodeId: '01HZZZEPISODE00000000000000', presetId: DEFAULT_PRESET_ID, quality: 'MASTER',
        reportProgress: noProgress, signal: noAbort,
      }),
    ).rejects.toThrow(/not found/i)
  }, 30_000)

  it.skipIf(!ffmpeg.available)('stitches a full episode from rendered scenes losslessly', async () => {
    const env = makeEnv('episode')
    const frameFile = join(env.dir, 'frame.png')
    writeFileSync(frameFile, makePng(32, 32, [130, 200, 240]))
    // A dedicated episode whose every scene has a built timeline.
    const episode = env.creative.createEpisode({ season: 1, number: 2, title: 'Two-parter' })
    for (const title of ['Part one', 'Part two']) {
      const scene = env.creative.createScene(episode.id, { title })
      const shot = env.storyboard.createShot(scene.id, { title: `${title} shot`, durationSeconds: 1 })
      env.storyboard.importFrame(shot.id, frameFile)
      env.timeline.buildFromScene(scene.id)
    }
    const result = await env.render.renderEpisode({
      episodeId: episode.id,
      presetId: DEFAULT_PRESET_ID,
      quality: 'PREVIEW',
      reportProgress: noProgress,
      signal: noAbort,
    })
    expect(result.kind).toBe('EPISODE')
    expect(result.sceneTitles).toEqual(['Part one', 'Part two'])
    const probed = env.render.probeDuration(result.outputPath)
    expect(probed).toBeGreaterThan(1.5)
    expect(probed).toBeLessThan(2.6)
    expect(existsSync(result.outputPath)).toBe(true)
  }, 120_000)
})
